// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ArbitrageDetector.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Arbitrage
    {
        /// <summary>
        /// Initializes a new instance of the Arbitrage class.
        /// </summary>
        public Arbitrage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Arbitrage class.
        /// </summary>
        public Arbitrage(CrossRate ask = default(CrossRate), CrossRate bid = default(CrossRate))
        {
            Ask = ask;
            Bid = bid;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ask")]
        public CrossRate Ask { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bid")]
        public CrossRate Bid { get; private set; }

    }
}
