// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ArbitrageDetector.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CrossRate
    {
        /// <summary>
        /// Initializes a new instance of the CrossRate class.
        /// </summary>
        public CrossRate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CrossRate class.
        /// </summary>
        public CrossRate(string source = default(string), string assetPair = default(string), double? bestBid = default(double?), double? bestAsk = default(double?), string conversionPath = default(string), System.DateTime? timestamp = default(System.DateTime?), IList<OrderBook> originalOrderBooks = default(IList<OrderBook>))
        {
            Source = source;
            AssetPair = assetPair;
            BestBid = bestBid;
            BestAsk = bestAsk;
            ConversionPath = conversionPath;
            Timestamp = timestamp;
            OriginalOrderBooks = originalOrderBooks;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Source")]
        public string Source { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AssetPair")]
        public string AssetPair { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BestBid")]
        public double? BestBid { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "BestAsk")]
        public double? BestAsk { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ConversionPath")]
        public string ConversionPath { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Timestamp")]
        public System.DateTime? Timestamp { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OriginalOrderBooks")]
        public IList<OrderBook> OriginalOrderBooks { get; private set; }

    }
}
