// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ArbitrageDetector.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OrderBook
    {
        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderBook class.
        /// </summary>
        public OrderBook(string source = default(string), string asset = default(string), System.DateTime? timestamp = default(System.DateTime?), IList<VolumePrice> asks = default(IList<VolumePrice>), IList<VolumePrice> bids = default(IList<VolumePrice>))
        {
            Source = source;
            Asset = asset;
            Timestamp = timestamp;
            Asks = asks;
            Bids = bids;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "source")]
        public string Source { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asset")]
        public string Asset { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "timestamp")]
        public System.DateTime? Timestamp { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "asks")]
        public IList<VolumePrice> Asks { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "bids")]
        public IList<VolumePrice> Bids { get; private set; }

    }
}
