// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.ArbitrageDetector.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class VolumePrice
    {
        /// <summary>
        /// Initializes a new instance of the VolumePrice class.
        /// </summary>
        public VolumePrice()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the VolumePrice class.
        /// </summary>
        public VolumePrice(double? price = default(double?), double? volume = default(double?))
        {
            Price = price;
            Volume = volume;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public double? Price { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "volume")]
        public double? Volume { get; private set; }

    }
}
